import { PALETTE } from '@faber-ui/tokens';

import type { TTheme } from './theme.types';

export const DARK_THEME = {
  BACKGROUND_PRIMARY: PALETTE.NEUTRAL_950,
  SURFACE_PRIMARY: PALETTE.NEUTRAL_900,
  TEXT_PRIMARY: PALETTE.NEUTRAL_50,
  TEXT_SECONDARY: PALETTE.NEUTRAL_300,
  TEXT_DISABLED: PALETTE.NEUTRAL_500,
  BORDER_DEFAULT: PALETTE.NEUTRAL_700,
  BORDER_STRONG: PALETTE.NEUTRAL_600,
  DISABLED_BACKGROUND: PALETTE.NEUTRAL_800,
  FOCUS_RING: PALETTE.COPPER_100,
  ERROR: PALETTE.RED_100,
  OVERLAY: PALETTE.OVERLAY_800,
  PRIMARY: PALETTE.MALACHITE_100,
  PRIMARY_HOVER: PALETTE.MALACHITE_200,
  PRIMARY_ACTIVE: PALETTE.MALACHITE_300,
  ON_PRIMARY: PALETTE.NEUTRAL_950,
  ACCENT: PALETTE.COPPER_100,
  ACCENT_HOVER: PALETTE.COPPER_200,
  ACCENT_ACTIVE: PALETTE.COPPER_300,
  ON_ACCENT: PALETTE.NEUTRAL_950,
} as const satisfies TTheme;
