import { PALETTE } from '@faber-ui/tokens';

import type { TTheme } from './theme.types';

export const DARK_THEME = {
  BACKGROUND_PRIMARY: PALETTE.GREEN_600,
  SURFACE_PRIMARY: PALETTE.NEUTRAL_900,
  TEXT_PRIMARY: PALETTE.NEUTRAL_50,
  TEXT_SECONDARY: PALETTE.NEUTRAL_300,
  TEXT_DISABLED: PALETTE.NEUTRAL_500,
  BORDER_DEFAULT: PALETTE.NEUTRAL_700,
  BORDER_STRONG: PALETTE.NEUTRAL_600,
  DISABLED_BACKGROUND: PALETTE.NEUTRAL_800,
  FOCUS_RING: PALETTE.PURPLE_100,
  PRIMARY: PALETTE.GREEN_100,
  PRIMARY_HOVER: PALETTE.GREEN_200,
  PRIMARY_ACTIVE: PALETTE.GREEN_300,
  ON_PRIMARY: PALETTE.GREEN_600,
  ACCENT: PALETTE.PURPLE_100,
  ACCENT_HOVER: PALETTE.PURPLE_200,
  ACCENT_ACTIVE: PALETTE.PURPLE_300,
  ON_ACCENT: PALETTE.PURPLE_600,
} as const satisfies TTheme;
