import { PALETTE } from '@faber-ui/tokens';

import type { TTheme } from './theme.types';

export const LIGHT_THEME = {
  BACKGROUND_PRIMARY: PALETTE.NEUTRAL_50,
  SURFACE_PRIMARY: PALETTE.WHITE,
  TEXT_PRIMARY: PALETTE.NEUTRAL_950,
  TEXT_SECONDARY: PALETTE.NEUTRAL_600,
  TEXT_DISABLED: PALETTE.NEUTRAL_500,
  BORDER_DEFAULT: PALETTE.NEUTRAL_200,
  BORDER_STRONG: PALETTE.NEUTRAL_400,
  DISABLED_BACKGROUND: PALETTE.NEUTRAL_200,
  FOCUS_RING: PALETTE.COPPER_400,
  ERROR: PALETTE.RED_400,
  PRIMARY: PALETTE.MALACHITE_400,
  PRIMARY_HOVER: PALETTE.MALACHITE_500,
  PRIMARY_ACTIVE: PALETTE.MALACHITE_600,
  ON_PRIMARY: PALETTE.WHITE,
  ACCENT: PALETTE.COPPER_400,
  ACCENT_HOVER: PALETTE.COPPER_500,
  ACCENT_ACTIVE: PALETTE.COPPER_600,
  ON_ACCENT: PALETTE.WHITE,
} as const satisfies TTheme;
