import { PALETTE } from '@faber-ui/tokens';
import { describe, expect, it } from 'vitest';

import { DARK_THEME } from './dark-theme';
import { LIGHT_THEME } from './light-theme';

describe('color themes', () => {
  it('provides the approved light theme foundation', () => {
    expect(LIGHT_THEME).toEqual({
      BACKGROUND_PRIMARY: PALETTE.NEUTRAL_50,
      SURFACE_PRIMARY: PALETTE.WHITE,
      TEXT_PRIMARY: PALETTE.NEUTRAL_950,
      TEXT_SECONDARY: PALETTE.NEUTRAL_700,
      TEXT_DISABLED: PALETTE.NEUTRAL_500,
      BORDER_DEFAULT: PALETTE.NEUTRAL_200,
      BORDER_STRONG: PALETTE.NEUTRAL_400,
      DISABLED_BACKGROUND: PALETTE.NEUTRAL_200,
      FOCUS_RING: PALETTE.PURPLE_400,
      PRIMARY: PALETTE.GREEN_400,
      PRIMARY_HOVER: PALETTE.GREEN_500,
      PRIMARY_ACTIVE: PALETTE.GREEN_600,
      ON_PRIMARY: PALETTE.WHITE,
      ACCENT: PALETTE.PURPLE_400,
      ACCENT_HOVER: PALETTE.PURPLE_500,
      ACCENT_ACTIVE: PALETTE.PURPLE_600,
      ON_ACCENT: PALETTE.WHITE,
    });
  });

  it('provides the approved dark theme foundation', () => {
    expect(DARK_THEME).toEqual({
      BACKGROUND_PRIMARY: PALETTE.GREEN_600,
      SURFACE_PRIMARY: PALETTE.NEUTRAL_900,
      TEXT_PRIMARY: PALETTE.NEUTRAL_50,
      TEXT_SECONDARY: PALETTE.NEUTRAL_300,
      TEXT_DISABLED: PALETTE.NEUTRAL_500,
      BORDER_DEFAULT: PALETTE.NEUTRAL_700,
      BORDER_STRONG: PALETTE.NEUTRAL_600,
      DISABLED_BACKGROUND: PALETTE.NEUTRAL_800,
      FOCUS_RING: PALETTE.PURPLE_100,
      PRIMARY: PALETTE.GREEN_100,
      PRIMARY_HOVER: PALETTE.GREEN_200,
      PRIMARY_ACTIVE: PALETTE.GREEN_300,
      ON_PRIMARY: PALETTE.GREEN_600,
      ACCENT: PALETTE.PURPLE_100,
      ACCENT_HOVER: PALETTE.PURPLE_200,
      ACCENT_ACTIVE: PALETTE.PURPLE_300,
      ON_ACCENT: PALETTE.PURPLE_600,
    });
  });
});
