import { PALETTE } from '@faber-ui/tokens';
import { describe, expect, it } from 'vitest';

import { DARK_THEME } from './dark-theme';
import { LIGHT_THEME } from './light-theme';

describe('color themes', () => {
  it('SHOULD provide the approved light theme foundation', () => {
    expect(LIGHT_THEME).toEqual({
      BACKGROUND_PRIMARY: PALETTE.NEUTRAL_50,
      SURFACE_PRIMARY: PALETTE.WHITE,
      TEXT_PRIMARY: PALETTE.NEUTRAL_950,
      TEXT_SECONDARY: PALETTE.NEUTRAL_600,
      TEXT_DISABLED: PALETTE.NEUTRAL_500,
      BORDER_DEFAULT: PALETTE.NEUTRAL_200,
      BORDER_STRONG: PALETTE.NEUTRAL_500,
      DISABLED_BACKGROUND: PALETTE.NEUTRAL_200,
      FOCUS_RING: PALETTE.OBSIDIAN_400,
      ERROR: PALETTE.RED_400,
      OVERLAY: PALETTE.OVERLAY_400,
      PRIMARY: PALETTE.AMETHYST_400,
      PRIMARY_HOVER: PALETTE.AMETHYST_500,
      PRIMARY_ACTIVE: PALETTE.AMETHYST_600,
      ON_PRIMARY: PALETTE.WHITE,
      ACCENT: PALETTE.OBSIDIAN_400,
      ACCENT_HOVER: PALETTE.OBSIDIAN_500,
      ACCENT_ACTIVE: PALETTE.OBSIDIAN_600,
      ON_ACCENT: PALETTE.WHITE,
    });
  });

  it('SHOULD provide the approved dark theme foundation', () => {
    expect(DARK_THEME).toEqual({
      BACKGROUND_PRIMARY: PALETTE.NEUTRAL_950,
      SURFACE_PRIMARY: PALETTE.NEUTRAL_900,
      TEXT_PRIMARY: PALETTE.NEUTRAL_50,
      TEXT_SECONDARY: PALETTE.NEUTRAL_300,
      TEXT_DISABLED: PALETTE.NEUTRAL_500,
      BORDER_DEFAULT: PALETTE.NEUTRAL_700,
      BORDER_STRONG: PALETTE.NEUTRAL_500,
      DISABLED_BACKGROUND: PALETTE.NEUTRAL_800,
      FOCUS_RING: PALETTE.OBSIDIAN_100,
      ERROR: PALETTE.RED_100,
      OVERLAY: PALETTE.OVERLAY_800,
      PRIMARY: PALETTE.AMETHYST_100,
      PRIMARY_HOVER: PALETTE.AMETHYST_75,
      PRIMARY_ACTIVE: PALETTE.AMETHYST_50,
      ON_PRIMARY: PALETTE.NEUTRAL_950,
      ACCENT: PALETTE.OBSIDIAN_100,
      ACCENT_HOVER: PALETTE.OBSIDIAN_200,
      ACCENT_ACTIVE: PALETTE.OBSIDIAN_300,
      ON_ACCENT: PALETTE.NEUTRAL_950,
    });
  });
});
